spring.application.name=grocery_app
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?user=postgres.bufzhfajosnibsveharh&password=Noobingrocery10809
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.address=0.0.0.0
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
